APP = ui
APP_PATH = sys

PROGRAMS = ui
GRAPHICS = mindstorms Ani1x screen playrecent_screen file_screen apps_screen \
           settings_screen 144x65_POP3 144x82_POP4 16x178_BRICKAPPS_BAN \
		   16x178_FILE_BAN 16x178_PLAYLAST_BAN 16x178_SETTINGS_BAN
SOUNDS = Click DownloadSucces GeneralAlarm OverpowerAlert PowerDown Startup

screen_SOURCE = 115x178_MainMenuBottom
playrecent_screen_SOURCE = 115x178_EV3MainMenu_PLAYLAST_BUTTON
file_screen_SOURCE = 115x178_EV3MainMenu_FILESYSTEM_BUTTON
apps_screen_SOURCE = 115x178_EV3MainMenu_BRICKAPPS_BUTTON
settings_screen_SOURCE = 115x178_EV3MainMenu_TOOLS_BUTTON

playlast_SOURCE = 16x178_PLAYLAST_BAN
file_SOURCE = 16x178_FILE_BAN
brickapp_SOURCE = 16x178_SETTINGS_BAN
settings_SOURCE = 16x178_BRICKAPPS_BAN



include ../rules.mk
