#!/bin/bash
# AO - Run this script to setup codesourcery.

profile0=~/.profile

if [ -d ~/CodeSourcery ]
then
	echo "CodeSourcery directory exists, no need to unpack"
else
	echo "Extracting..."
	unzip -d ~/ CodeSourcery.zip
	echo "Done."
fi

echo "Adding Code Sourcey to path..."


echo "Sourcing profile"
check=`cat ~/.profile | grep -o "CodeSourcery"`

if [ -n '$check' ]
then
	echo "Code Sourcery found in path, no need to source"
	echo "Done."
else
	if [ -e $profile0 ]
	then
		echo "Found profile definition, appending"
		echo 'PATH=$PATH:~/CodeSourcery/Sourcery_G++_Lite/bin' >> $profile0
	else
		echo "No profile found, creating $profile0"
		echo 'PATH=$PATH:~/CodeSourcery/Sourcery_G++_Lite/bin' > $profile0
	fi
	source $profile0
fi

echo "Done."
