#!/bin/bash
# AO - Run this script to setup codesourcery.

profile0=~/.profile

if [ -d ~/CodeSourcery ]
then
	echo "CodeSourcery directory exists, no need to unpack"
else
	echo "Extracting..."
	unzip -d ~/ CodeSourcery.zip
	echo "Done."
fi

echo "Adding Code Sourcey to path..."

if [ -e $profile0 ]
then
	echo "Found profile definition, appending"
	echo 'PATH=$PATH:~/CodeSourcery/Sourcery_G++_Lite/bin' >> $profile0
else
	echo "No profile found, creating $profile0"
	echo 'PATH=$PATH:~/CodeSourcery/Sourcery_G++_Lite/bin' > $profile0
fi

source $profile0

echo "Done."
echo "Please restart terminal to ensure path update."
