#! /bin/bash
BASE = ..

# Setup directories
source env_setup

#cp ${AM1808_KERNEL}/drivers/usb/gadget/g_hid.ko ~/projects/lms2012/lms2012/Linux_AM1808/mod/g_hid.ko

cp -r $(BASE)/lms2012/Linux_AM1808/* ~/projects/${AM1808_DISTRO}/filesys/home/root/lms2012




